# Generated by Django 4.2 on 2025-01-25 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=20)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=6)),
                ('description', models.TextField()),
                ('characteristics', models.CharField(blank=True, choices=[('Playful', 'Playful'), ('Shy', 'Shy'), ('Friendly', 'Friendly'), ('Active', 'Active'), ('Lazy', 'Lazy'), ('Independent', 'Independent'), ('Loyal', 'Loyal'), ('Intelligent', 'Intelligent')], max_length=100, null=True)),
                ('energy_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium Low'), (3, 'Medium'), (4, 'Medium High'), (5, 'High')], default=3)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets_images/')),
                ('location', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('care_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='petcare.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
