# Generated by Django 4.2 on 2025-01-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='pet',
            name='characteristics',
            field=models.ManyToManyField(blank=True, to='petcare.characteristic'),
        ),
    ]
