# Generated by Django 4.2 on 2025-01-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0003_alter_pet_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='color',
        ),
    ]
