# Generated by Django 4.2 on 2025-01-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0004_remove_pet_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='pets_images/doggo.jpeg', upload_to='pets_images/'),
            preserve_default=False,
        ),
    ]
